os: osx
language: bash
cache: bundle 
before_install: brew update
install: 
  - brew install lame
script: 
  - cd genspeech
  - ./genspeech EN Alex
  - ./genspeech EN Samantha
  - ./genspeech EN Agnes
  - ./genspeech EN Fiona
  - ./genspeech EN Karen
  - ./genspeech EN Kathy
  - ./genspeech EN Moira
  - ./genspeech EN Princess
  - ./genspeech EN Vicki
  - ./genspeech EN Victoria
  - ./genspeech EN Daniel
  - ./genspeech EN Fred
  - ./genspeech EN Amelie
  - ./genspeech EN Cellos 
  - ./genspeech EN Ellen 
  - ./genspeech EN Monica
  - ./genspeech EN Tessa
  - ./genspeech EN Veena
  - ./genspeech EN Alice
  - ./genspeech EN Ralph 
  - cd ..
  - say -v ?
before_deploy:
  - mkdir release/
  - mv genspeech/*.zip release/
  - cp iopage/* release/
  - cd release && ../create_index.sh && cd ..
deploy:
  provider: pages
  repo: vidzo/github.io
  target_branch: master
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: release
  on:
    branch: master
